linters-settings:
  govet:
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 20
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: modifies-parameter
      - name: unreachable-code
      - name: struct-tag
      - name: constant-logical-expr
      - name: bool-literal-in-expr
      - name: redefines-builtin-id
      - name: imports-blacklist
      - name: range-val-in-closure
      - name: range-val-address
      - name: waitgroup-by-value
      - name: atomic
      - name: call-to-gc
      - name: duplicated-imports
      - name: string-of-int
      - name: defer
      - name: unconditional-recursion
      - name: identical-branches

linters:
  disable-all: true
  enable:
    - revive           # Replacement for deprecated golint
    - unconvert
    - goconst
    - misspell
    - unparam
    - gofmt
    - goimports
    - gocyclo
    - govet
    - unused
    - ineffassign
    - staticcheck
    - errcheck
    - gosimple

issues:
  exclude-use-default: false
  max-same-issues: 10
